//! Error definitions


/// Union of all errors generated by this lib
#[derive(Debug)]
pub enum Error {
    /// Reference frequency outside of the allowed range
    InvalidReferenceFrequency,
    /// Output frequency outside of the allowed range
    InvalidOutputFrequency,
    /// SPI communication error
    Spi,
    /// Pin toggle error (should never happen)
    Pin,
}
